// <auto-generated />
using BikePackJournal.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BikePackJournal.Migrations
{
    [DbContext(typeof(BikePackDBContext))]
    [Migration("20181118182949_InitialModel")]
    partial class InitialModel
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("BikePackJournal.Models.BikeMake", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("BikeMakes");
                });

            modelBuilder.Entity("BikePackJournal.Models.BikeModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("BikeMakeId");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.HasIndex("BikeMakeId");

                    b.ToTable("BikeModels");
                });

            modelBuilder.Entity("BikePackJournal.Models.BikeModel", b =>
                {
                    b.HasOne("BikePackJournal.Models.BikeMake", "BikeMake")
                        .WithMany("Models")
                        .HasForeignKey("BikeMakeId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
